### PR TITLE
claimed ~del for ~novrud-hanweb

### PR DESCRIPTION
**Pull request by yebyen**
PGP key and a thank-you note posted on urbit-dev list!

### CODE REVIEW

**Comment by yebyen** [comment]
Oops... the thank-you note was only posted to the short list of people included in the announcement.

If anyone else wants a copy of my PGP key, I'll find a reasonable way to get it to you...

**Comment by yebyen** [comment]
I am not sure this patch is needed or exactly correct, but it seems to work as expected -- passing -p 59001 launches ames with port 59001, passing without -p chooses a random port.

Is there any reason to be worried that the struct might not initialize `ops_u.por_s` field to zero, if something bad happens?

**Comment by kingdonb** [comment]
There was a C code change that got mixed in because of the way I did my pull request -- just in case it was not noticed.  I am sure it's fine, it works for me, but maybe someone wants to look at it?

Also maybe we can have a wiki page for how to use :pope... it seems pretty straight forward but I wasn't sure if there is any important significance to the generator string.  Is it secret, should I keep it, etc.

I've just used it but I wasn't prepared to give a passphrase, so left it blank, and just guessing it's a no-op unless you actually add the fingerprint to the source code... it looks deterministic on the passphrase.  What does one do to bring up their carrier after the fingerprint is saved and merged?

**Comment by cgyarvin** [comment]
You do need the passphrase - otherwise, that's like having an empty root
password.

To run, simply vere -I ~del - the I is for "imperial," of course. :-)
 You'll also need del.urbit.org to resolve to your IP - John can help you
with that.

**Pull request merged**
