### PR TITLE
Bypass ames.c:319 c3_assert fail

### PR DESCRIPTION
**Pull request by yebyen**
This change was needed to make my Ubuntu chroot hosted under an Android able to create a pier.
It's not for merging, unless these sections are really useless on every platform, I doubted this just a bit.

My Android system is KatKiss 4.3 (dev) on a Transformer TF-101.  I created the chroot using Linux Deploy from the store: https://play.google.com/store/apps/details?id=ru.meefik.linuxdeploy

### CODE REVIEW

**Comment by johncburnham** [comment]
CGY made another change today that fixes this. Slightly different fix, but does effectively the same thing.

**Comment by yebyen** [comment]
Thanks.  It does not have the same effect for me, though.  Unless he's made it in a branch I haven't seen?

I believed you and just went ahead and untagged my branch for that commit to clean up the network graph a bit, so it seems like that commit is gone for my git client.  Maybe there's a way to retrieve it.  The Github link still works, but I've lost all of my local and remote refs to that commit.  Fortunately it was a pretty trivial change to start again.

The latest change I have in your `outside/libuv` is Aug 21, "checked in libuv" -- I read the list entry where CGY said he was patching upstream code and he didn't like it, so I guess it just wasn't committed.

**Comment by yebyen** [comment]
I don't want to be that guy who says "go back and read the list entries on Oct 1" but I just have done that for my own benefit, since my git-fu is also weak, and it's been really helpful for me to understand how to mold commits around GitHub pull requests and keep the history clean with rebase.

I think this basically couldn't happen if you were using feature branches (it looks like we accidentally closed a pull request/issue without actually merging any fix for the issue).

This is the thread that helped me: https://groups.google.com/forum/#!topic/urbit-dev/iEoRVRuiGgU

**Comment by cgyarvin** [comment]
No, I'm an idiot and forgot to commit it.  I just did.  **linux** is
#defined on Android, right?

**Comment by yebyen** [comment]
It is.  Definitely works now.  Thanks.

**Pull request closed without merging**
