### PR TITLE
cleaned up weld a bit, it was doing uncessary homo operations

### PR DESCRIPTION
**Pull request by ericfode**

### CODE REVIEW

**Comment by cgyarvin** [comment]
That's a little daring for a novice Hooner!  Actually, it is doing unnecessary homo operations.  But this is heavy territory and the fix is not quite right.  Also it doesn't really matter, as weld is jet-propelled.  Alas, I am going to reject a PR for the first time.  But not without an A for effort...

**Comment by ericfode** [comment]
If you would not mind I would love to know what was wrong with it so I can improve my understanding of hoon.

**Comment by cgyarvin** [comment]
It now reads:
-  =>  .(a (homo a), b (homo b))

It should probably read:
-  =>  .(a `(homo a)`a, b `(homo b)`b)

Ie, just cast it instead of actually doing it.  But it's a somewhat
delicate area, doing inference at this level (even Haskell can't really do
it) and I am not terribly inclined to fix right now.

I don't think your code would compile - instead of resetting a and b, which
are there, we try to modify c and d which don't exist.

You can test your own hoon.hoon with

:reset

Be sure to :reload %batz to also get your libraries renewed.

**Comment by ericfode** [comment]
=+ does not add them to scope?

**Comment by cgyarvin** [comment]
There is no scope - it's not Lisp here.  =+ is just nock operator 8,
basically.  =+  x replaces your subject s with [x s].  Thus, =+ foo=bar
gives you [foo=bar s].  We search the head first when looking for %foo, and
find your bar.

. is the subject itself.  .(x y, z q) is the subject with the limbs x and z
modified to have the values y and q.  Thus, on top of the subject you are
pushing another copy of the subject, modifying limbs in that copy that
don't actually exist.  So, it may look pretty but it actually ain't...

**Pull request closed without merging**
